dia = input('Qual dia você nasceu ? ')
mes =  input('Qual mês você nasceu ? ')
ano = input('Qual ano você nasceu ? ')
print(dia + '/' + mes + '/' + ano)
print('vc nasceu dia' + dia + 'de' + mes + 'de' + ano)